language: rust
rust: stable

jobs:
  include:
    - os: linux
      dist: bionic

    - os: osx

    - os: windows

before_script:
  - rustup component add rustfmt

script:
  - cargo build  --no-default-features --features 'encryption'
  - cargo fmt --all -- --check
  - cargo test --no-default-features --features 'encryption'
