[package]
authors = ["Damir Jelić <poljar@termina.org.uk"]
description = "A high level Matrix client-server library."
edition = "2018"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "MIT"
name = "matrix-sdk"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
version = "0.1.0"

[dependencies]
js_int = "0.1.2"
futures = "0.3.4"
reqwest = "0.10.1"
http = "0.2.0"
async-std = "1.5.0"
ruma-api = "0.13.0"
ruma-client-api = "0.6.0"
ruma-events = "0.15.0"
log = "0.4.8"

ruma-identifiers = "0.14.1"
serde_json = "1.0.48"
serde_urlencoded = "0.6.1"
url = "2.1.1"

[dependencies.serde]
version = "1.0.104"
features = ["derive"]

[dev-dependencies]
tokio = { version = "0.2.11", features = ["full"] }
url = "2.1.1"
mockito = "0.23.3"
