[package]
authors = ["Damir Jelić <poljar@termina.org.uk"]
description = "A high level Matrix client library."
edition = "2018"
homepage = "https://github.com/poljar/nio-rust"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "MIT"
name = "matrix-nio"
readme = "README.md"
repository = "https://github.com/poljar/nio-rust"
version = "0.1.0"

[dependencies]
js_int = "0.1.2"
futures = "0.3.1"
reqwest = "0.10.0-alpha.2"
http = "0.1.19"
async-std = "1.2.0"
ruma-api = "0.12.0-alpha.1"
ruma-client-api = "0.5.0-alpha.1"
ruma-events = "0.15.1"
log = "0.4.8"

ruma-identifiers = "0.14.0"
serde_json = "1.0.42"
serde_urlencoded = "0.6.1"
url = "2.1.0"

[dependencies.serde]
version = "1.0.103"
features = ["derive"]

[dev-dependencies]
tokio = "0.2.0-alpha.6"
url = "2.1.0"
mockito = "0.22.0"
