[package]
authors = ["Damir Jelić <poljar@termina.org.uk"]
description = "A high level Matrix client library."
edition = "2018"
homepage = "https://github.com/poljar/nio-rust"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "MIT"
name = "matrix-nio"
readme = "README.md"
repository = "https://github.com/poljar/nio-rust"
version = "0.1.0"

[dependencies]
js_int = "0.1.2"
futures-preview = "0.3.0-alpha.18"
reqwest = "0.10.0-alpha.1"
http = "0.1.18"
ruma-api = "0.11.0"
ruma-client-api = "0.4.0"
ruma-events = "0.15.1"
log = "0.4.8"

ruma-identifiers = "*"
serde_json = "1.0.40"
serde_urlencoded = "0.6.1"
url = "2.1.0"

[dependencies.serde]
version = "1.0.101"
features = ["derive"]

[dev-dependencies]
tokio = "0.2.0-alpha.6"
