[package]
authors = ["Damir Jelić <poljar@termina.org.uk"]
description = "A high level Matrix client-server library."
edition = "2018"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "MIT"
name = "matrix-sdk"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
version = "0.1.0"

[features]
default = []
encryption = ["olm-rs", "serde/derive", "serde_json", "cjson", "async-trait"]
sqlite-cryptostore = ["sqlx", "zeroize"]

[dependencies]
futures = "0.3.4"
reqwest = "0.10.4"
http = "0.2.0"
url = "2.1.1"

js_int = "0.1.3"
ruma-api = "0.14.0"
ruma-client-api = { version = "0.6.0", git = "https://github.com/matrix-org/ruma-client-api/" }
ruma-events = "0.17.0"
ruma-identifiers = "0.14.1"

thiserror = "1.0.11"
zeroize = { version = "1.1.0", optional = true }
async-trait = { version = "0.1.24", optional = true }

olm-rs = { path = "/home/poljar/werk/matrix/olm-rs", optional = true, features = ["serde"]}
serde = { version = "1.0.104", optional = true, features = ["derive"] }
serde_json = { version = "1.0.48", optional = true }
cjson = { version = "0.1.0", optional = true }

[dependencies.tokio]
version = "0.2.13"
default-features = false
features = ["sync", "time"]

[dependencies.sqlx]
git = "https://github.com/launchbadge/sqlx/"
optional = true
default-features = false
features = ["runtime-tokio", "sqlite"]

[dev-dependencies]
tokio = { version = "0.2.13", features = ["rt-threaded", "macros"] }
tempfile = "3.1.0"
mockito = "0.23.3"
