[package]
name = "nio-olm-sys"
version = "3.1.4-beta"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
description = "Low level bindings for the Olm C library"
license = "ISC"
edition = "2018"
build = "build.rs"

[build-dependencies]
bindgen = "0.51.1"

[dependencies]
libc = "0.2.65"
